### ISSUE TITLE
Split in feature commands

### ISSUE THREAD

**Issue by RibalGZ** [emvigo/plog#12]
Splitting plog in several commands will be easier to mantain, easier for scripting and easier to implement a better stdin/stdout integration.
I propose the following commands:

- plog-init
- plog-write
- plog-read

**Comment by emvigo** [comment]
You're probably right, and I see the point, but this would probably require a huge rewrite of main.c. Maybe in some future this might be feasable? I'm not closing the issue until things become much clearer whether this might or might not be possible.
Thanks for your feedback!
